### PR TITLE
Add copy hex value feature

### PR DESCRIPTION
**Pull request by pepas24**
I implemented the copy feature using clipboard.js as suggested in #6 I think this is very helpful to pass that values to a design apps or to code.

### CODE REVIEW

**Comment by edelstone** [comment]
@pepas24 I'll pull it down and take a look today some time. Thank you for the contribution!

**Comment by edelstone** [comment]
(Above revert was a mistake)

@pepas24 I like it, thank you!

I wouldn't mind if, when you click a table cell and successfully copy the hex color, a tooltip briefly appeared saying "Copied!", or something like that - but I'll make another issue for that.

Thanks again!

**Comment by pepas24** [comment]
>I wouldn't mind if, when you click a table cell and successfully copy the hex color, a tooltip briefly appeared saying "Copied!", or something like that.

You are right! I also think on that but I didn't want to add javascript or much markup, but I can add it, maybe in a few days I can check it out.

**Comment by edelstone** [comment]
No worries or obligation @pepas24. Thanks for the work you've done. I made an issue at #9.

**Pull request merged**
