### PR TITLE
Add checkbox that allows users to copy with hashtags.

### PR DESCRIPTION
**Pull request by AleksandrHovhannisyan**
Related issue: #13

Demo:

demo

Feel free to suggest changes!

### CODE REVIEW

**Comment by edelstone** [comment]
Haven’t checked locally yet but a couple quick questions:

1. Does tabbing to the checkbox and selecting/deselecting with keyboard work smoothly?
2. If checked, is that remembered by the browser in any way? Or is the default always just unchecked?

**Comment by AleksandrHovhannisyan** [comment]
Good questions! I think I may have only subscribed to clicks; lemme check and update that if necessary. I always forget about keyboard users :D

Re: the second question, the default is always unchecked; we could use localStorage to remember the user's selection, if you'd like. (Note that this won't work in IE 6-7.)

**Comment by AleksandrHovhannisyan** [comment]
Okay, just checked—yup, tabbing and clicking with Enter works.

**Comment by edelstone** [comment]
I definitely wouldn't care about IE 6 or 7 :)

But let's just make a new issue if that's something we want to do.

Checking the PR shortly.

**Comment by edelstone** [comment]
Thanks @AleksandrHovhannisyan. I tried my hardest to break it and it seemed very robust!

Feel free to file more issues if you see more improvements you'd like.

**Comment by AleksandrHovhannisyan** [comment]
Sounds good!

**Pull request merged**
