### PR TITLE
Share colour palette

### PR DESCRIPTION
**Pull request by joelcarr**
A colleague shared your tool with me today and I thought it would be nice to be able to share colour palettes with the URL.

When a user makes tints and shades with their hex codes, it will store those hex codes as a comma separated list in the URL hash (ie `https://maketintsandshades.com/#ffffff,000000,ff9900`).

When a user visits the tool with a comma separated list of hex codes, it will pre populate the textarea with their hex codes separated by spaces (ie the previous url would set the text area value as `ffffff 000000 ff9900`).

### CODE REVIEW

**Comment by edelstone** [comment]
Thanks @joelcarr; this is useful. I will admit – I expected the link to submit the form and show the results, in addition to populating the text area. Is that difficult to achieve?

**Comment by joelcarr** [comment]
I have it now so the results show on page load 👍

**Comment by edelstone** [comment]
LGTM @joelcarr.

Thanks for being the first outsider to contribute!

**Comment by joelcarr** [comment]
My pleasure!

**Pull request merged**
