### PR TITLE
Better Error Messaging

### PR DESCRIPTION
**Pull request by TJScalzo**
I created a warning that appears when the form is submitted with no content. I also updated the scrolling logic so that it only scrolls down when colors are generated. Otherwise, it scrolls up to show the warning.

@edelstone should clicking the button with an empty text area clear the URL hash? Currently, refreshing the page after a color has previously been entered causes it to reappear because it is still in the URL.

(Fixes issue #3.)

### CODE REVIEW

**Comment by TJScalzo** [comment]
Also, I just did what made sense for the copy and the style of the warning. I'm open to suggestions for improving/simplifying the warning.

**Comment by edelstone** [comment]
@TJScalzo I'm not concerned with style and copy; that stuff is well inside my wheelhouse. The other stuff - not so much.

Here are some thoughts:

1. The warning message blocks functionality of the label. Currently you can click the "Enter hex colors..." label and the text area focuses, as you'd expect. By using opacity alone to hide/show the warning, that functionality is physically blocked across most of the label.
2. Based on how you have this working, yes, I do think that the URL should reset if the colors are no longer present. If that's not hard to implement, that'd be a good addition imo.
3. Overall, it seems like a nice improvement, thanks again!

**Comment by edelstone** [comment]
Also, I'm not totally sold on `autofocus` when the page loads. Not sure if that would be confusing for screen readers or other accessibility use cases. Is that required for your changes to work properly?

**Comment by TJScalzo** [comment]
> 1. The warning message blocks functionality of the label. Currently you can click the "Enter hex colors..." label and the text area focuses, as you'd expect. By using opacity alone to hide/show the warning, that functionality is physically blocked across most of the label.

I will fix this. I completely forgot that labels serve a functional purpose in forms.
<br>
>2. Based on how you have this working, yes, I do think that the URL should reset if the colors are no longer present. If that's not hard to implement, that'd be a good addition imo.

It's not difficult to implement at all. I will include it in my next commit.
<br>
> Also, I'm not totally sold on `autofocus` when the page loads. Not sure if that would be confusing for screen readers or other accessibility use cases. Is that required for your changes to work properly?

It isn't required. I just thought it made sense for it to gain focus on page load since it's the only input. I will undo it so that it doesn't impact accessibility.

**Comment by edelstone** [comment]
You can leave the autofocus if you want. As long as it doesn’t impact the rest of your work I can just change it later (if it’s bothering me).

**Comment by TJScalzo** [comment]
I removed it because I understand how it could mess up a screen reader. When the page loads focus is sucked below the title and instructions directly to an input. I just made it so that the text area is refocused when the warning appears. 

**Edit:** I also commented the javascript I added. So like you said, you can always change it later.

**Comment by edelstone** [comment]
Couple regressions I'm noticing when navigating around without a mouse:

1. Enter a valid hex code into the text area and then tab to the submit button using the keyboard. Hit enter when the button is focused. Enter key appears to break the full scroll to the color table. It's like the enter key is behaving like spacebar would in this situation.
2. Follow the steps from the scenario above, and then delete the hex code from the text area so it's blank. Tab to focus the button and press the enter key. The color table and URL do not clear as they would if using the mouse.

These behaviors work well/as-intended in the present version, so feel free to refer to that.

**Comment by TJScalzo** [comment]
Interesting... Safari doesn't focus the submit button at all, even in the present version. I don't know why, but I thought this was the intended behavior for some reason. Opening the page in Firefox I can now see the true intended behavior which makes much more sense.

I will troubleshoot the cause of the regressions using Firefox. But I also created a new issue (#17) about the trouble with Safari.

**Comment by edelstone** [comment]
Thanks for making the new issue. I can't reproduce that, so we can check on that one later. if you have any questions about intended behavior just let me know.

**Comment by TJScalzo** [comment]
> 1. Enter a valid hex code into the text area and then tab to the submit button using the keyboard. Hit enter when the button is focused. Enter key appears to break the full scroll to the color table. It's like the enter key is behaving like spacebar would in this situation.

This issue is caused by d30eb6b. Since the user is able to interrupt the scroll animation, the enter key is seen as the user trying to interrupt the scroll animation. Rolling back that commit solves this problem. 
<br>
> 2. Follow the steps from the scenario above, and then delete the hex code from the text area so it's blank. Tab to focus the button and press the enter key. The color table and URL do not clear as they would if using the mouse.

I'm not exactly sure what caused this issue. But undoing the changes of d30eb6b also solves this issue.

**Comment by edelstone** [comment]
I overlooked that commit. Maybe spacebar is a better candidate to stop the animation. I'm also fine just not having it.

**Comment by TJScalzo** [comment]
Any `keyup` event would be seen as the user trying to interrupt the scrolling. It would require more work to specify just the spacebar as stopping the animation. It's much simpler to just remove the interruption functionality entirely for now. I can work on adding it back later if it's sorely missed.

**Comment by edelstone** [comment]
LGTM

**Pull request merged**
