### PR TITLE
Scroll to codes when loading a custom link

### PR DESCRIPTION
**Pull request by TJScalzo**
Implements the features described in issue #16. 

This change also happens to fix a slight scrolling bug when submitting an empty input where the page scrolls down and then back up.

### CODE REVIEW

**Comment by TJScalzo** [comment]
Note: This change means the first color of the table will also be focused whenever the submit button is pressed. The focusing isn't exclusive to when the page loads. It keeps functionality consistent between custom links and manual code generation.

**Comment by edelstone** [comment]
I don't mind the focus being on the first cell; I think that makes sense. But does the copy button need to be visible? That bugs me.

**Comment by TJScalzo** [comment]
Do you want the copy button to only appear after the user interacts with the cells? Like they have to tab to another element or hover over the first cell for the copy button to appear?

**Comment by TJScalzo** [comment]
I don't know if hiding the first cell's copy button is a good idea. If the user presses tab, the first copy button that they see is on the second cell. This would make it seem like they have to tab away and then back to copy the first color. When in reality, hitting enter would still copy the first cell, even when the copy icon isn't visible. Overall, I think this will confuse users.

**Comment by edelstone** [comment]
Can the table be focused then, instead of the first cell? Yeah basically I'd like the copy buttons to only show if they have been interacted with.

**Comment by edelstone** [comment]
Not sure if you're ready for a review, but I see a couple issues initially:

1. The scroll to the color table is now more of a jump. To see the effect in an exaggerated way, throw like 10 hex colors in the text area and hit the submit button. You will see that there's a big jump instead of a gentle scroll to the table.
2. I think you probably want `outline: 0` on the `.ts-colors` div instead of `#tints-and-shades` where you have it.

**Comment by TJScalzo** [comment]
> 1. The scroll to the color table is now more of a jump. To see the effect in an exaggerated way, throw like 10 hex colors in the text area and hit the submit button. You will see that there's a big jump instead of a gentle scroll to the table.

This is because it's focusing an element that's partially out of view of the window so the page is jumping to show it. I'm fixing it by delaying the focus until after the scrolling is done.
<br>

> 2. I think you probably want `outline: 0` on the `.ts-colors` div instead of `#tints-and-shades` where you have it.

I based the focus styles on a trick I found [here](https://codepen.io/kizu/pen/OgzMeQ?editors=1100). It makes it so that it can be focused using the keyboard, but not by clicking on it. Do you think I should do it differently? Would it be better to just not show a focus outline at all?

**Comment by edelstone** [comment]
> I based the focus styles on a trick I found here. It makes it so that it can be focused using the keyboard, but not by clicking on it. Do you think I should do it differently? Would it be better to just not show a focus outline at all?

I shouldn't have gotten technical. I suppose my issue is that focus outlines are visible around the table whether arriving at a custom link or searching for a color from scratch. I'm testing in Chrome so far. If you need more details let me know.

**Comment by edelstone** [comment]
Just to clarify, here's what I'm seeing in Chrome. After clicking the button or after using a custom link, I see the outline around the table:
Screen Shot 2019-10-18 at 10 03 17 AM
When I place the `outline: 0` rule on `.ts-colors` (parent) instead of `#tints-and-shades` (child), the outline goes away. The only problem with that is that the element no longer has an outline when keyboard tabbing. That seems like the opposite of what the Codepen you shared is trying to do, i.e. hide the outline _unless_ using the keyboard.

**Comment by TJScalzo** [comment]
> Just to clarify, here's what I'm seeing in Chrome. After clicking the button or after using a custom link, I see the outline around the table:

This is exactly how I intended the outline to work. Anytime the table of colors is generated, it puts focus on the table. You can tab into the colors. back to the submit button and text area, or return focus to the table. But when you click on the area around the table, you don't randomly focus an element that you can't interact with. The table only gains focus when the user intends to use their keyboard. 


> When I place the `outline: 0` rule on `.ts-colors` (parent) instead of `#tints-and-shades` (child), the outline goes away. The only problem with that is that the element no longer has an outline when keyboard tabbing. That seems like the opposite of what the Codepen you shared is trying to do, i.e. hide the outline _unless_ using the keyboard.

I'm not sure I understand why you want to put `outline: 0` on `.ts-colors` instead of `#tints-and-shades`. The way I implemented right now follows what the Codepen is trying to do. 

<hr>

@edelstone I think we've confused each other. I didn't fully understand what you wanted and you didn't fully understand what I was trying to do. I should have asked for more specifics at the beginning. Do you want focus to be put on the table only when the page loads and then focus to never be able to return to the table once it loses focus? Can you describe the exact behavior you're imagining?

**Comment by edelstone** [comment]
Basically the way it behaves now is good. However, it would be better if there weren't any focus outlines on the table _unless_ the keyboard was being used to tab to the table. However, in that scenario, it would be _even_ better if the table simply weren't tabbable at all, as it has no functionality on it's own. Does that makes sense?

**Comment by TJScalzo** [comment]
I understand now. The table should gain focus when the colors are generated and the page scrolls down to them. But once it loses focus the user shouldn't be able to focus it again manually.

**Comment by edelstone** [comment]
@TJScalzo Yep, sorry for any confusion. This is functioning and looking how I would expect it to when using the mouse or keyboard. Tested on Chrome, FF, Safari, Mobile Safari. Well done!

**Comment by edelstone** [comment]
Closes #16

**Pull request merged**
